name: Dev Manual Build Docker

on:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev

      # Docker Image 构建环境
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push
      - name: Build dockerfile
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            allanpk716/chinesesubfinder:dev0916b01